# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/virtual-tuneup"
site: Virtual TuneUp
email: "support@virtualtuneup.net"
description: Services for Maintaining Peak Performance in Organizations
url: http://virtualtuneup.net
exclude: [ /yarn.lock, .package.json, .package-lock.json, node_modules ]
markdown: kramdown
timezone: America/Los_Angeles
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
